# Generated by Django 5.2.4 on 2025-07-25 16:34

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
