# Generated by Django 5.2.4 on 2025-07-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
